import type { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Wireless Earbuds Pro',
    description: 'Noise-cancelling earbuds with 28-hour battery life.',
    price: 2999,
    salePrice: 2499,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80'],
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 42,
    variations: [
      { id: 'v1', name: 'Color', value: 'Black', priceAdjustment: 0, stock: 20 },
      { id: 'v2', name: 'Color', value: 'White', priceAdjustment: 100, stock: 22 },
    ],
    vendorId: 'vendor-1',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'USB-C Fast Charger 65W',
    description: 'Compact GaN charger compatible with phones and laptops.',
    price: 1499,
    salePrice: null,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80'],
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 80,
    variations: [],
    vendorId: 'vendor-1',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    name: 'Screen Guard Pack',
    description: 'Tempered glass pack for popular smartphone models.',
    price: 399,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80'],
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 0,
    variations: [],
    vendorId: 'vendor-1',
    status: 'out_of_stock',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    name: 'Organic Face Serum',
    description: 'Hydrating serum from a local beauty boutique.',
    price: 899,
    salePrice: 749,
    images: ['https://images.unsplash.com/photo-1620916569870-0d1e0d0e0e0e?w=800&q=80'],
    category: 'Beauty',
    categorySlug: 'services',
    stock: 35,
    variations: [],
    vendorId: 'vendor-1',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Handcrafted Desk Lamp',
    description: 'Warm LED lamp for home offices.',
    price: 1899,
    salePrice: null,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80'],
    category: 'Home & Living',
    categorySlug: 'services',
    stock: 18,
    variations: [],
    vendorId: 'vendor-1',
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
